<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Edit Task - Personal Task Manager</title>
                <script src="https://cdn.tailwindcss.com"></script>
                </head>
                <body class="bg-gray-100 min-h-screen py-8">
                    <div class="max-w-xl mx-auto px-4">
                            <div class="bg-white p-6 rounded-lg shadow border">
                                        <h1 class="text-xl font-bold mb-4 text-gray-800">Edit Task</h1>
                                                    
                                                                <form action="https://super-tribble-xrpxx4jqjg79f5gg-8001.app.github.dev/tasks/{{ $task->id }}" method="POST">
                                                                                @csrf
                                                                                                @method('PUT')
                                                                                                                
                                                                                                                                <div class="mb-4">
                                                                                                                                                    <label class="block text-sm font-medium text-gray-600 mb-1">Task Name</label>
                                                                                                                                                                        <input type="text" name="task_name" value="{{ $task->task_name }}" required class="w-full border rounded-md p-2 text-sm">
                                                                                                                                                                                        </div>

                                                                                                                                                                                                        <div class="mb-4">
                                                                                                                                                                                                                            <label class="block text-sm font-medium text-gray-600 mb-1">Due Date</label>
                                                                                                                                                                                                                                                <input type="date" name="due_date" value="{{ $task->due_date }}" class="w-full border rounded-md p-2 text-sm">
                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                <div class="mb-4">
                                                                                                                                                                                                                                                                                                    <label class="block text-sm font-medium text-gray-600 mb-1">Description</label>
                                                                                                                                                                                                                                                                                                                        <textarea name="description" rows="3" class="w-full border rounded-md p-2 text-sm">{{ $task->description }}</textarea>
                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                        <div class="mb-4">
                                                                                                                                                                                                                                                                                                                                                                            <label class="block text-sm font-medium text-gray-600 mb-1">Status</label>
                                                                                                                                                                                                                                                                                                                                                                                                <select name="status" class="w-full border rounded-md p-2 text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                        <option value="Pending" {{ $task->status == 'Pending' ? 'selected' : '' }}>Pending</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                <option value="Completed" {{ $task->status == 'Completed' ? 'selected' : '' }}>Completed</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div class="flex space-x-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button type="submit" class="bg-blue-600 text-white px-4 py-2 rounded-md text-sm font-medium hover:bg-blue-700">Update Task</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <a href="https://super-tribble-xrpxx4jqjg79f5gg-8001.app.github.dev/tasks" class="bg-gray-300 text-gray-700 px-4 py-2 rounded-md text-sm font-medium hover:bg-gray-400">Cancel</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </body>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </html>